

spring:
  profiles:
    active: tut1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000

rabbitmq:
  queue:
    name: "hello"
    json:
      name: "hello_json"
  exchange:
    name: "hello_exchange"
  routing:
    key:
      name: "hello_routing_key"
      json:
        name: "hello_json_routing_key"








