

spring:
  profiles:
    active: tut1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000

rabbitmq:
  queue:
    name: "hello"
  exchange:
    name: "hello_exchange"
  routing:
    key:
      name: "hello_routing_key"





